INSERT INTO CHARACTER_VOTE (ID, NAME, VOTE_COUNT) VALUES (1, 'Hulk', 123)
INSERT INTO CHARACTER_VOTE (ID, NAME, VOTE_COUNT) VALUES (2, 'Thor', 13)
INSERT INTO CHARACTER_VOTE (ID, NAME, VOTE_COUNT) VALUES (3, 'Spider-Man', 493)